/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-11 02:41:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substringBefore", org.apache.taglibs.standard.functions.Functions.class, "substringBefore", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/Users/jeong-gwang-yeong/Documents/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/nkidol/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/Users/jeong-gwang-yeong/Documents/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/nkidol/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/Users/jeong-gwang-yeong/Documents/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/nkidol/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673125571922L));
    _jspx_dependants.put("/layout/navbar.jsp", Long.valueOf(1673404805000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("<link type=\"text/css;\" rel=\"stylesheet\" href=\"/css/style.css\" />\n");
      out.write("<title>日韓アイドル</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-light shadow-lg sticky-top\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<a class=\"navbar-brand \" href=\"/main\"><img src=\"/images/jkpop.png\"\n");
      out.write("				alt=\"\" /></a>\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("				aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("						aria-current=\"page\" href=\"/main\">ホーム</a></li>\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle text-primary\" \n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" disabled>\n");
      out.write("							韓アイドル </a>\n");
      out.write("						<ul class=\"dropdown-menu dropend\">\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\" >１９９０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=1990&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=1990&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０００年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=2000&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=2000&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０１０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=2010&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=2010&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０２０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=2020&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=2020&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle text-danger\" disabled\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							日アイドル </a>\n");
      out.write("						<ul class=\"dropdown-menu dropend\">\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">１９９０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=1990&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=1990&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０００年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=2000&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=2000&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０１０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=2010&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=2010&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０２０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=2020&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=2020&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"/board/list\">掲示板</a>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content rounded-4 shadow\">\n");
      out.write("				<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("					<h1 class=\"fw-bold mb-0 fs-2\">ログイン</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"modal-body p-5 pt-0\">\n");
      out.write("					<form action=\"/user/login\"\n");
      out.write("						onsubmit=\"loginFormSubmit(this); return false;\" method=\"post\">\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputLoginId\"\n");
      out.write("								name=\"userID\" placeholder=\"ID\"> <label\n");
      out.write("								for=\"floatingInputLoginId\">ID</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"password\" class=\"form-control rounded-3\"\n");
      out.write("								id=\"floatingLoginPassword\" name=\"userPassword\" placeholder=\"Password\">\n");
      out.write("							<label for=\"floatingLoginPassword\">PASSWORD</label>\n");
      out.write("						</div>\n");
      out.write("						<button class=\"w-100 mb-2 btn btn-lg rounded-3 btn-primary\"\n");
      out.write("							type=\"submit\">LOG IN</button>\n");
      out.write("						<hr class=\"my-4\">\n");
      out.write("						<ul>\n");
      out.write("						<li><a class=\"text-primary\" role=\"button\" data-bs-target=\"#findById\" data-bs-toggle=\"modal\"\n");
      out.write("						>IDを忘れた方はこちら</a></li>\n");
      out.write("						<li><a class=\"text-primary\" role=\"button\" data-bs-target=\"#findByPw\" data-bs-toggle=\"modal\"\n");
      out.write("						>PASSWORDを忘れた方はこちら</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"modal fade\" id=\"findById\"  tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" >\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content rounded-4 shadow\">\n");
      out.write("				<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("					<h1 class=\"fw-bold mb-0 fs-2\">IDを忘れた方</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"modal-body p-5 pt-0\">\n");
      out.write("					<form action=\"/user/findById\"\n");
      out.write("						onsubmit=\"findByIdFormSubmit(this); return false;\" method=\"post\">\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<div class=\"form-floating mb-3 col\">\n");
      out.write("							<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputFirst\"\n");
      out.write("								name=\"userFirstName\" placeholder=\"FirstName\"><label\n");
      out.write("								for=\"floatingInputFirst\">FirstName</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating col\">\n");
      out.write("								<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputLast\"\n");
      out.write("								name=\"userLastName\" placeholder=\"LastName\"><label\n");
      out.write("								for=\"floatingInputLast\">LastName</label>\n");
      out.write("								</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"email\" class=\"form-control rounded-3\"\n");
      out.write("								id=\"floatingEmail\" name=\"userEmail\" placeholder=\"E-mail\">\n");
      out.write("							<label for=\"floatingEmail\">E-mail</label>\n");
      out.write("						</div>\n");
      out.write("						<button class=\"w-100 mb-2 btn btn-lg rounded-3 btn-primary\"\n");
      out.write("							type=\"submit\">送信</button>\n");
      out.write("					</form>\n");
      out.write("						<hr class=\"my-4\">\n");
      out.write("						<a class=\"text-primary\" role=\"button\" data-bs-target=\"#findByPw\" data-bs-toggle=\"modal\"\n");
      out.write("						>PASSWORDを忘れた方はこちら</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div><div class=\"modal fade\" id=\"findByPw\"  tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" >\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content rounded-4 shadow\">\n");
      out.write("				<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("					<h1 class=\"fw-bold mb-0 fs-2\">Passwordを忘れた方</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"modal-body p-5 pt-0\">\n");
      out.write("					<form action=\"/user/findByPw\"\n");
      out.write("						onsubmit=\"findByPwFormSubmit(this); return false;\" method=\"post\">\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputFindPw\"\n");
      out.write("								name=\"userID\" placeholder=\"ID\"> <label\n");
      out.write("								for=\"floatingInputFindPw\">ID</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"email\" class=\"form-control rounded-3\"\n");
      out.write("								id=\"floatingFindPwEmail\" name=\"userEmail\" placeholder=\"E-mail\">\n");
      out.write("							<label for=\"floatingFindPwEmail\">E-mail</label>\n");
      out.write("						</div>\n");
      out.write("						<button class=\"w-100 mb-2 btn btn-lg rounded-3 btn-primary\"\n");
      out.write("							type=\"submit\">送信</button>\n");
      out.write("					</form>\n");
      out.write("						<hr class=\"my-4\">\n");
      out.write("						<a class=\"text-primary\" role=\"button\" data-bs-target=\"#findById\" data-bs-toggle=\"modal\"\n");
      out.write("						>IDを忘れた方はこちら</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container subnav mt-4\">\n");
      out.write("	<div class=\"row\">\n");
      out.write("		<div class=\"col-md-3 sm-12\">\n");
      out.write("			<div class=\"pe-5 bg-white\">\n");
      out.write("				<span class=\"fs-5 fw-semibold\">HOME</span>\n");
      out.write("				<div class=\"border-top my-3\"></div>\n");
      out.write("				<ul class=\"list-unstyled ps-0\">\n");
      out.write("					<li class=\"mb-1 pb-3\">\n");
      out.write("						<button\n");
      out.write("							class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed \n");
      out.write("							text-primary krButton\"\n");
      out.write("							data-bs-toggle=\"collapse\" data-bs-target=\"#idolkr-collapse\"\n");
      out.write("							aria-expanded=\"false\">韓アイドル</button>\n");
      out.write("						<div class=\"collapse\" id=\"idolkr-collapse\">\n");
      out.write("							<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender1990-collapse\" aria-expanded=\"false\">1990年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender1990-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/korea/year1990/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/korea/year1990/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender2000-collapse\" aria-expanded=\"false\">2000年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender2000-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/korea/year2000/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/korea/year2000/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender2010-collapse\" aria-expanded=\"false\">2010年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender2010-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/korea/year2010/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/korea/year2010/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender2020-collapse\" aria-expanded=\"false\">2020年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender2020-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/korea/year2020/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/korea/year2020/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"mb-1 pb-3\">\n");
      out.write("						<button\n");
      out.write("							class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed \n");
      out.write("							text-danger jpButton\"\n");
      out.write("							data-bs-toggle=\"collapse\" data-bs-target=\"#idoljp-collapse\"\n");
      out.write("							aria-expanded=\"false\">日アイドル</button>\n");
      out.write("						<div class=\"collapse\" id=\"idoljp-collapse\">\n");
      out.write("							<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender1990-collapse\" aria-expanded=\"false\">1990年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender1990-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/japan/year1990/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/japan/year1990/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender2000-collapse\" aria-expanded=\"false\">2000年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender2000-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/japan/year2000/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/japan/year2000/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender2010-collapse\" aria-expanded=\"false\">2010年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender2010-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/japan/year2010/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/japan/year2010/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("								<li class=\"p-1\"><button\n");
      out.write("										class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\"\n");
      out.write("										data-bs-toggle=\"collapse\"\n");
      out.write("										data-bs-target=\"#gender2020-collapse\" aria-expanded=\"false\">2020年代</button>\n");
      out.write("									<div class=\"collapse\" id=\"gender2020-collapse\">\n");
      out.write("										<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("											<li><a href=\"/album/japan/year2020/boy\">BoyGroup</a></li>\n");
      out.write("											<li><a href=\"/album/japan/year2020/girl\">GrilGroup</a></li>\n");
      out.write("											<li></li>\n");
      out.write("										</ul>\n");
      out.write("									</div></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"border-top my-3\"></li>\n");
      out.write("					<li class=\"mb-1\">\n");
      out.write("						<button\n");
      out.write("							class=\"btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed\n");
      out.write("							text-success\"\n");
      out.write("							data-bs-toggle=\"collapse\" data-bs-target=\"#account-collapse\"\n");
      out.write("							aria-expanded=\"false\">アクセス</button>\n");
      out.write("						<div class=\"collapse\" id=\"account-collapse\">\n");
      out.write("							<ul class=\"btn-toggle-nav list-unstyled fw-normal pb-1 small\">\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col\">\n");
      out.write("			<form class=\"d-flex m-2 justify-content-end\" role=\"search\">\n");
      out.write("				<fieldset class=\"d-flex\">\n");
      out.write("					<legend hidden=\"hidden\">検索フィールド</legend>\n");
      out.write("					<label hidden=\"hideen\">検索分類</label> <select\n");
      out.write("						class=\"form-select form-select-sm me-2\"\n");
      out.write("						aria-label=\"Default select example\" name=\"field\">\n");
      out.write("						<option ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(param.field == \"title\")?\"selected\":\"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" value=\"title\">タイトル</option>\n");
      out.write("						<option ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(param.field == \"userID\")?\"selected\":\"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" value=\"userID\">作成者</option>\n");
      out.write("					</select> <label hidden=\"hidden\">検索</label> <input class=\"form-control me-2\"\n");
      out.write("						type=\"search\" name=\"query\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.query}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("					<button class=\"btn btn-outline-primary mysearch\" type=\"submit\">検索</button>\n");
      out.write("				</fieldset>\n");
      out.write("			</form>\n");
      out.write("\n");
      out.write("			<table class=\"col-md-4 table table-striped table-hover\"\n");
      out.write("				style=\"text-align: center; border: #dddddd\">\n");
      out.write("				<thead>\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"background-color: #eeeeee; text-align: center;\">番号</th>\n");
      out.write("						<th style=\"background-color: #eeeeee; text-align: center;\">タイトル</th>\n");
      out.write("						<th style=\"background-color: #eeeeee; text-align: center;\">作成者</th>\n");
      out.write("						<th style=\"background-color: #eeeeee; text-align: center;\">日付</th>\n");
      out.write("					</tr>\n");
      out.write("				</thead>\n");
      out.write("				<tbody>\n");
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				</tbody>\n");
      out.write("			</table>\n");
      out.write("\n");
      out.write("			<div class=\"row gx-0\">\n");
      out.write("\n");
      out.write("				<div class=\"col\">\n");
      out.write("					<a href=\"?p=1\" class=\"btn btn-success btn-arraw-left float-start\">トップページ</a>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"col\">\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					<nav aria-label=\"Page navigation example\">\n");
      out.write("						<ul class=\"pagination justify-content-center\">\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</ul>\n");
      out.write("					</nav>\n");
      out.write("				</div>\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f10(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("	integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"/js/modalFocus.js\"></script>\n");
      out.write("<script src=\"/js/app.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /layout/navbar.jsp(107,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty principal}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"nav-item dropdown pe-3\">\n");
          out.write("						<button class=\"btn btn-primary dropdown-toggle\" type=\"button\"\n");
          out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">ログイン</button>\n");
          out.write("						<ul class=\"dropdown-menu\">\n");
          out.write("							<li><a class=\"dropdown-item text-start\" role=\"button\" data-bs-toggle=\"modal\"\n");
          out.write("								data-bs-target=\"#myModal\" aria-expanded=\"false\">ログイン</a></li>\n");
          out.write("							<li><a class=\"dropdown-item text-start\" href=\"/user/join_view\">会員登録</a></li>\n");
          out.write("						</ul>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /layout/navbar.jsp(118,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty principal}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"nav-item dropdown\">\n");
          out.write("						");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("						<button class=\"btn btn-primary dropdown-toggle\" type=\"button\"\n");
          out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">会員管理</button>\n");
          out.write("						<ul class=\"dropdown-menu dropdown-menu-end\">\n");
          out.write("							<li class=\"dropdown-divider\"></li>\n");
          out.write("\n");
          out.write("							<li><a class=\"dropdown-item text-start\" href=\"/user/logout\">ログアウト</a></li>\n");
          out.write("						</ul>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /layout/navbar.jsp(120,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!isEmailCheck}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							<a href=\"/user/emailSend\" class=\"btn btn-danger\" role=\"button\"\n");
          out.write("								onclick=\"clickEmailSendMSG();\">E-MAIL確認</a>\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/view/board/list.jsp(133,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty principal }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<li class=\"p-1\"><a href=\"#\"\n");
          out.write("									data-bs-toggle=\"modal\"\n");
          out.write("								data-bs-target=\"#myModal\" aria-expanded=\"false\">ログイン</a></li>\n");
          out.write("								<li class=\"p-1\"><a href=\"/user/join_view\">会員登録</a></li>\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/view/board/list.jsp(139,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty principal }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<li class=\"p-1\"><a href=\"/user/logout\">ログアウト</a></li>\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/board/list.jsp(175,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("n");
      // /WEB-INF/view/board/list.jsp(175,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/board/list.jsp(175,5) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("						<tr>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td><a href=\"detail?bbsID=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</a></td>\n");
            out.write("							<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.userID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("							<td>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("						</tr>\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/board/list.jsp(178,43) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/board/list.jsp(181,11) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy/MM/dd hh:mm:ss");
      // /WEB-INF/view/board/list.jsp(181,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${n.regDate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/view/board/list.jsp(195,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("page");
      // /WEB-INF/view/board/list.jsp(195,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/board/list.jsp(195,5) '${(empty param.p)?1:param.p }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${(empty param.p)?1:param.p }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/view/board/list.jsp(196,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("startNum");
      // /WEB-INF/view/board/list.jsp(196,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/board/list.jsp(196,5) '${page-(page-1)%5}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${page-(page-1)%5}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/view/board/list.jsp(197,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("lastNum");
      // /WEB-INF/view/board/list.jsp(197,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/board/list.jsp(197,5) '${fn:substringBefore(Math.ceil(count/10),'.') }'",_jsp_getExpressionFactory().createValueExpression(new org.apache.jasper.el.ELContextWrapper(_jspx_page_context.getELContext(),_jspx_fnmap_0),"${fn:substringBefore(Math.ceil(count/10),'.') }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/view/board/list.jsp(199,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("active");
      // /WEB-INF/view/board/list.jsp(199,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/board/list.jsp(199,5) 'active'",_jsp_getExpressionFactory().createValueExpression("active",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/view/board/list.jsp(202,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum > 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<li class=\"page-item\"><a class=\"page-link\"\n");
          out.write("									href=\"?p=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum-1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" aria-label=\"Previous\"> <span\n");
          out.write("										aria-hidden=\"true\">&laquo;</span>\n");
          out.write("								</a></li>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/view/board/list.jsp(208,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      // /WEB-INF/view/board/list.jsp(208,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(0);
      // /WEB-INF/view/board/list.jsp(208,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(4);
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								");
            if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/view/board/list.jsp(209,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum+i<=lastNum }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("									<li class=\"page-item\"><a\n");
          out.write("										class=\"page-link ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(param.p==startNum+i)?active:''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\n");
          out.write("										href=\"?p=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum+i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum+i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></li>\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/view/board/list.jsp(215,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum+4 < lastNum}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<li class=\"page-item\"><a class=\"page-link\"\n");
          out.write("									href=\"?p=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${startNum+5}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" aria-label=\"Next\"> <span\n");
          out.write("										aria-hidden=\"true\">&raquo;</span>\n");
          out.write("								</a></li>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /WEB-INF/view/board/list.jsp(224,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty principal && isEmailCheck}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"col\">\n");
          out.write("						<a href=\"write_view\" class=\"btn btn-primary float-end\"\n");
          out.write("							role=\"button\">作成</a>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f9_reused = false;
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent(null);
      // /WEB-INF/view/board/list.jsp(230,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty principal && !isEmailCheck}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"col\">\n");
          out.write("						<button type=\"button\" class=\"btn btn-primary float-end\"\n");
          out.write("							data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">作成</button>\n");
          out.write("						<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\n");
          out.write("							aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
          out.write("							<div class=\"modal-dialog\">\n");
          out.write("								<div class=\"modal-content\">\n");
          out.write("									<div class=\"modal-header\">\n");
          out.write("										<button type=\"button\" class=\"btn-close\"\n");
          out.write("											data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
          out.write("									</div>\n");
          out.write("									<div class=\"modal-body\">\n");
          out.write("										掲示板に投稿するためにはE-MAILの確認が必要です。<br> 右上のE-MAILボタンを押して確認してください。\n");
          out.write("									</div>\n");
          out.write("									<div class=\"modal-footer\">\n");
          out.write("										<button type=\"button\" class=\"btn btn-secondary\"\n");
          out.write("											data-bs-dismiss=\"modal\">閉じる</button>\n");
          out.write("									</div>\n");
          out.write("								</div>\n");
          out.write("							</div>\n");
          out.write("						</div>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      _jspx_th_c_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f10_reused = false;
    try {
      _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f10.setParent(null);
      // /WEB-INF/view/board/list.jsp(254,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty principal}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
      if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"col\">\n");
          out.write("						<button type=\"button\" class=\"btn btn-primary float-end\"\n");
          out.write("							data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">作成</button>\n");
          out.write("						<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\n");
          out.write("							aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
          out.write("							<div class=\"modal-dialog\">\n");
          out.write("								<div class=\"modal-content\">\n");
          out.write("									<div class=\"modal-header\">\n");
          out.write("										<button type=\"button\" class=\"btn-close\"\n");
          out.write("											data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
          out.write("									</div>\n");
          out.write("									<div class=\"modal-body\">ログインしてください</div>\n");
          out.write("									<div class=\"modal-footer\">\n");
          out.write("										<button class=\"btn btn-primary\" data-bs-toggle=\"modal\"\n");
          out.write("											data-bs-target=\"#myModal\" aria-expanded=\"false\">ログイン</button>\n");
          out.write("										<button type=\"button\" class=\"btn btn-secondary\"\n");
          out.write("											data-bs-dismiss=\"modal\">閉じる</button>\n");
          out.write("									</div>\n");
          out.write("								</div>\n");
          out.write("							</div>\n");
          out.write("						</div>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
      _jspx_th_c_005fif_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f10_reused);
    }
    return false;
  }
}
