/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-12 03:09:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/includes/sidebar.jsp", Long.valueOf(1673492464000L));
    _jspx_dependants.put("/WEB-INF/views/includes/footer.jsp", Long.valueOf(1673492295000L));
    _jspx_dependants.put("/WEB-INF/views/includes/navToolbar.jsp", Long.valueOf(1673492937000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>JKPOP</title>\n");
      out.write("	<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("    <!-- Custom fonts for this template-->\n");
      out.write("    <link href=\"/resources/pages/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\n");
      out.write("        rel=\"stylesheet\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/462b5b874f.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <!-- Custom styles for this template-->\n");
      out.write("    <link href=\"/resources/pages/css/sb-admin-2.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<!-- side bar -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body id=\"page-top\">\n");
      out.write("\n");
      out.write("    <!-- Page Wrapper -->\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("        <!-- Sidebar -->\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-dark sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\n");
      out.write("\n");
      out.write("            <!-- Sidebar - Brand -->\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"/main\">\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\n");
      out.write("                   <img src=\"/resources/images/jkpop.png\"\n");
      out.write("				alt=\"\" />\n");
      out.write("                </div>\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\"><sup>日韓</sup><br>JK POP </div>\n");
      out.write("            </a>\n");
      out.write("\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\n");
      out.write("\n");
      out.write("            <!-- Nav Item - Dashboard -->\n");
      out.write("            <li class=\"nav-item active\">\n");
      out.write("                <a class=\"nav-link\" href=\"/main\">\n");
      out.write("                   <i class=\"fa-solid fa-house\"></i>\n");
      out.write("                    <span>HOME</span></a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("            <!-- Heading -->\n");
      out.write("            <div class=\"sidebar-heading\">\n");
      out.write("                Interface\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- K-POP -->\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseKorea\"\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseKorea\">\n");
      out.write("                   <i class=\"fa-solid fa-music\"></i>\n");
      out.write("                    <span>K-POP</span>\n");
      out.write("                </a>\n");
      out.write("                <div id=\"collapseKorea\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                        <h6 class=\"collapse-header\">Custom Components:</h6>\n");
      out.write("                         <a class=\"collapse-item\" href=\"buttons.html\">２０２０年代</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">２０１０年代</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">２０００年代</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">１９９０年代</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </li> <!-- J-POP -->\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseJapan\"\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseJapan\">\n");
      out.write("                   <i class=\"fa-solid fa-music\"></i>\n");
      out.write("                    <span>J-POP</span>\n");
      out.write("                </a>\n");
      out.write("                <div id=\"collapseJapan\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                        <h6 class=\"collapse-header\">Custom Components:</h6>\n");
      out.write("                        <a class=\"collapse-item\" href=\"buttons.html\">２０２０年代</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">２０１０年代</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">２０００年代</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">１９９０年代</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("            <!-- Nav Item - Tables -->\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"/board/list\">\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\n");
      out.write("                    <span>Tables</span></a>\n");
      out.write("            </li>\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <hr class=\"sidebar-divider\">\n");
      out.write("\n");
      out.write("            <!-- Heading -->\n");
      out.write("            <div class=\"sidebar-heading\">\n");
      out.write("                Addons\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\"\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapsePages\">\n");
      out.write("                    <i class=\"fas fa-fw fa-folder\"></i>\n");
      out.write("                    <span>Pages</span>\n");
      out.write("                </a>\n");
      out.write("                <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\n");
      out.write("                        <h6 class=\"collapse-header\">Login Screens:</h6>\n");
      out.write("                        <a class=\"collapse-item\" href=\"login.html\">Login</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"register.html\">Register</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\n");
      out.write("                        <div class=\"collapse-divider\"></div>\n");
      out.write("                        <h6 class=\"collapse-header\">Other Pages:</h6>\n");
      out.write("                        <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\n");
      out.write("                        <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <!-- Nav Item - Charts -->\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"charts.html\">\n");
      out.write("                    <i class=\"fas fa-fw fa-chart-area\"></i>\n");
      out.write("                    <span>Charts</span></a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            \n");
      out.write("\n");
      out.write("            <!-- Divider -->\n");
      out.write("            <hr class=\"sidebar-divider d-none d-md-block\">\n");
      out.write("\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\n");
      out.write("            </div>\n");
      out.write("        </ul>\n");
      out.write("        <!-- End of Sidebar -->");
      out.write('\n');
      out.write("\n");
      out.write(" <!-- Content Wrapper -->\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\n");
      out.write("\n");
      out.write("            <!-- Main Content -->\n");
      out.write("            <div id=\"content\">\n");
      out.write("\n");
      out.write("                <!-- Topbar -->\n");
      out.write("                <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\n");
      out.write("\n");
      out.write("                    <!-- Sidebar Toggle (Topbar) -->\n");
      out.write("                    <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\n");
      out.write("                        <i class=\"fa fa-bars\"></i>\n");
      out.write("                    </button>\n");
      out.write("\n");
      out.write("                    <!-- Topbar Navbar -->\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\n");
      out.write("\n");
      out.write("                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow d-sm-none\">\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\"\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-search fa-fw\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <!-- Dropdown - Messages -->\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\n");
      out.write("                                aria-labelledby=\"searchDropdown\">\n");
      out.write("                                <form class=\"form-inline mr-auto w-100 navbar-search\">\n");
      out.write("                                    <div class=\"input-group\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control bg-light border-0 small\"\n");
      out.write("                                            placeholder=\"Search for...\" aria-label=\"Search\"\n");
      out.write("                                            aria-describedby=\"basic-addon2\">\n");
      out.write("                                        <div class=\"input-group-append\">\n");
      out.write("                                            <button class=\"btn btn-primary\" type=\"button\">\n");
      out.write("                                                <i class=\"fas fa-search fa-sm\"></i>\n");
      out.write("                                            </button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                        <!-- Nav Item - Alerts -->\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow mx-1\">\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\"\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-bell fa-fw\"></i>\n");
      out.write("                                <!-- Counter - Alerts -->\n");
      out.write("                                <span class=\"badge badge-danger badge-counter\">3+</span>\n");
      out.write("                            </a>\n");
      out.write("                            <!-- Dropdown - Alerts -->\n");
      out.write("                            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n");
      out.write("                                aria-labelledby=\"alertsDropdown\">\n");
      out.write("                                <h6 class=\"dropdown-header\">\n");
      out.write("                                    Alerts Center\n");
      out.write("                                </h6>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"mr-3\">\n");
      out.write("                                        <div class=\"icon-circle bg-primary\">\n");
      out.write("                                            <i class=\"fas fa-file-alt text-white\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div class=\"small text-gray-500\">December 12, 2019</div>\n");
      out.write("                                        <span class=\"font-weight-bold\">A new monthly report is ready to download!</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"mr-3\">\n");
      out.write("                                        <div class=\"icon-circle bg-success\">\n");
      out.write("                                            <i class=\"fas fa-donate text-white\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div class=\"small text-gray-500\">December 7, 2019</div>\n");
      out.write("                                        $290.29 has been deposited into your account!\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"mr-3\">\n");
      out.write("                                        <div class=\"icon-circle bg-warning\">\n");
      out.write("                                            <i class=\"fas fa-exclamation-triangle text-white\"></i>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div class=\"small text-gray-500\">December 2, 2019</div>\n");
      out.write("                                        Spending Alert: We've noticed unusually high spending for your account.\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                        <!-- Nav Item - Messages -->\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow mx-1\">\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\"\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <i class=\"fas fa-envelope fa-fw\"></i>\n");
      out.write("                                <!-- Counter - Messages -->\n");
      out.write("                                <span class=\"badge badge-danger badge-counter\">7</span>\n");
      out.write("                            </a>\n");
      out.write("                            <!-- Dropdown - Messages -->\n");
      out.write("                            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n");
      out.write("                                aria-labelledby=\"messagesDropdown\">\n");
      out.write("                                <h6 class=\"dropdown-header\">\n");
      out.write("                                    Message Center\n");
      out.write("                                </h6>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_1.svg\"\n");
      out.write("                                            alt=\"...\">\n");
      out.write("                                        <div class=\"status-indicator bg-success\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"font-weight-bold\">\n");
      out.write("                                        <div class=\"text-truncate\">Hi there! I am wondering if you can help me with a\n");
      out.write("                                            problem I've been having.</div>\n");
      out.write("                                        <div class=\"small text-gray-500\">Emily Fowler · 58m</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_2.svg\"\n");
      out.write("                                            alt=\"...\">\n");
      out.write("                                        <div class=\"status-indicator\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div class=\"text-truncate\">I have the photos that you ordered last month, how\n");
      out.write("                                            would you like them sent to you?</div>\n");
      out.write("                                        <div class=\"small text-gray-500\">Jae Chun · 1d</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_3.svg\"\n");
      out.write("                                            alt=\"...\">\n");
      out.write("                                        <div class=\"status-indicator bg-warning\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div class=\"text-truncate\">Last month's report looks great, I am very happy with\n");
      out.write("                                            the progress so far, keep up the good work!</div>\n");
      out.write("                                        <div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\"\n");
      out.write("                                            alt=\"...\">\n");
      out.write("                                        <div class=\"status-indicator bg-success\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div>\n");
      out.write("                                        <div class=\"text-truncate\">Am I a good boy? The reason I ask is because someone\n");
      out.write("                                            told me that people say this to all dogs, even if they aren't good...</div>\n");
      out.write("                                        <div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read More Messages</a>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                        <div class=\"topbar-divider d-none d-sm-block\"></div>\n");
      out.write("\n");
      out.write("                        <!-- Nav Item - User Information -->\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow\">\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\"\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                <span class=\"mr-2 d-none d-lg-inline text-gray-600 small\">Douglas McGee</span>\n");
      out.write("                                <img class=\"img-profile rounded-circle\"\n");
      out.write("                                    src=\"/resources/pages/img/undraw_profile.svg\">\n");
      out.write("                            </a>\n");
      out.write("                            <!-- Dropdown - User Information -->\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\"\n");
      out.write("                                aria-labelledby=\"userDropdown\">\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                                    <i class=\"fas fa-user fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("                                    Profile\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                                    <i class=\"fas fa-cogs fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("                                    Settings\n");
      out.write("                                </a>\n");
      out.write("                                <div class=\"dropdown-divider\"></div>\n");
      out.write("                                <a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">\n");
      out.write("                                    <i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>\n");
      out.write("                                    Logout\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                </nav>\n");
      out.write("                <!-- End of Topbar -->");
      out.write("\n");
      out.write("       \n");
      out.write("\n");
      out.write("                <!-- Begin Page Content -->\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("                    <!-- Page Heading -->\n");
      out.write("                    <div class=\"d-sm-flex align-items-center justify-content-between mb-4\">\n");
      out.write("                        <h1 class=\"h3 mb-0 text-gray-800\">Rank</h1>\n");
      out.write("                        <a href=\"#\" class=\"d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm\"><i\n");
      out.write("                                class=\"fas fa-download fa-sm text-white-50\"></i> Generate Report</a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Content Row -->\n");
      out.write("                   <div class=\"container py-4\">\n");
      out.write("						<div class=\"row mt-4\">\n");
      out.write("							<div class=\"col-sm-5\">\n");
      out.write("								<div class=\"fs-1\">\n");
      out.write("									<img src=\"images/korea.png\" alt=\"\" />韓アイドル\n");
      out.write("								</div>\n");
      out.write("								<div id=\"carouselExampleSlidesOnly\" class=\"carousel slide\"\n");
      out.write("									data-bs-ride=\"carousel\">\n");
      out.write("									<div class=\"carousel-inner border p-2\">\n");
      out.write("										<div class=\"carousel-item active\" data-bs-interval=\"2000\">\n");
      out.write("											<img src=\"/resources/images/album/aespa.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("										</div>\n");
      out.write("										<div class=\"carousel-item \">\n");
      out.write("											<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kList.get(1).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("										</div>\n");
      out.write("										<div class=\"carousel-item\">\n");
      out.write("											<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kList.get(2).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("												class=\"d-block w-100 lesse\" alt=\"...\">\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("								<div class=\"col-sm-5 offset-sm-2\">\n");
      out.write("									<div class=\"fs-1\">\n");
      out.write("										<img src=\"images/japan.png\" alt=\"\" />日アイドル\n");
      out.write("									</div>\n");
      out.write("					\n");
      out.write("									<div id=\"carouselExampleSlidesOnly\" class=\"carousel slide\"\n");
      out.write("										data-bs-ride=\"carousel\">\n");
      out.write("										<div class=\"carousel-inner badge border p-2\">\n");
      out.write("											<div class=\"carousel-item active\" data-bs-interval=\"2000\">\n");
      out.write("												<img src=\"/resources/images/album/ive.png\" class=\"d-block w-100\"\n");
      out.write("													alt=\"...\">\n");
      out.write("											</div>\n");
      out.write("											<div class=\"carousel-item\">\n");
      out.write("												<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jList.get(1).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\"\n");
      out.write("													alt=\"...\">\n");
      out.write("											</div>\n");
      out.write("											<div class=\"carousel-item\">\n");
      out.write("												<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jList.get(2).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\"\n");
      out.write("													alt=\"...\">\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("                    <!-- Content Row -->\n");
      out.write("\n");
      out.write("                    <div class=\"row\">\n");
      out.write("\n");
      out.write("                        <!-- Area Chart -->\n");
      out.write("                        <div class=\"col-xl-8 col-lg-7\">\n");
      out.write("                            <div class=\"card shadow mb-4\">\n");
      out.write("                                <!-- Card Header - Dropdown -->\n");
      out.write("                                <div\n");
      out.write("                                    class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Earnings Overview</h6>\n");
      out.write("                                    <div class=\"dropdown no-arrow\">\n");
      out.write("                                        <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\"\n");
      out.write("                                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\n");
      out.write("                                        </a>\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\n");
      out.write("                                            aria-labelledby=\"dropdownMenuLink\">\n");
      out.write("                                            <div class=\"dropdown-header\">Dropdown Header:</div>\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Card Body -->\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"chart-area\">\n");
      out.write("                                        <canvas id=\"myAreaChart\"></canvas>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Pie Chart -->\n");
      out.write("                        <div class=\"col-xl-4 col-lg-5\">\n");
      out.write("                            <div class=\"card shadow mb-4\">\n");
      out.write("                                <!-- Card Header - Dropdown -->\n");
      out.write("                                <div\n");
      out.write("                                    class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Revenue Sources</h6>\n");
      out.write("                                    <div class=\"dropdown no-arrow\">\n");
      out.write("                                        <a class=\"dropdown-toggle\" href=\"#\" role=\"button\" id=\"dropdownMenuLink\"\n");
      out.write("                                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                                            <i class=\"fas fa-ellipsis-v fa-sm fa-fw text-gray-400\"></i>\n");
      out.write("                                        </a>\n");
      out.write("                                        <div class=\"dropdown-menu dropdown-menu-right shadow animated--fade-in\"\n");
      out.write("                                            aria-labelledby=\"dropdownMenuLink\">\n");
      out.write("                                            <div class=\"dropdown-header\">Dropdown Header:</div>\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Action</a>\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Another action</a>\n");
      out.write("                                            <div class=\"dropdown-divider\"></div>\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"#\">Something else here</a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Card Body -->\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"chart-pie pt-4 pb-2\">\n");
      out.write("                                        <canvas id=\"myPieChart\"></canvas>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"mt-4 text-center small\">\n");
      out.write("                                        <span class=\"mr-2\">\n");
      out.write("                                            <i class=\"fas fa-circle text-primary\"></i> Direct\n");
      out.write("                                        </span>\n");
      out.write("                                        <span class=\"mr-2\">\n");
      out.write("                                            <i class=\"fas fa-circle text-success\"></i> Social\n");
      out.write("                                        </span>\n");
      out.write("                                        <span class=\"mr-2\">\n");
      out.write("                                            <i class=\"fas fa-circle text-info\"></i> Referral\n");
      out.write("                                        </span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Content Row -->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("\n");
      out.write("                        <!-- Content Column -->\n");
      out.write("                        <div class=\"col-lg-6 mb-4\">\n");
      out.write("\n");
      out.write("                            <!-- Project Card Example -->\n");
      out.write("                            <div class=\"card shadow mb-4\">\n");
      out.write("                                <div class=\"card-header py-3\">\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Projects</h6>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Server Migration <span\n");
      out.write("                                            class=\"float-right\">20%</span></h4>\n");
      out.write("                                    <div class=\"progress mb-4\">\n");
      out.write("                                        <div class=\"progress-bar bg-danger\" role=\"progressbar\" style=\"width: 20%\"\n");
      out.write("                                            aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Sales Tracking <span\n");
      out.write("                                            class=\"float-right\">40%</span></h4>\n");
      out.write("                                    <div class=\"progress mb-4\">\n");
      out.write("                                        <div class=\"progress-bar bg-warning\" role=\"progressbar\" style=\"width: 40%\"\n");
      out.write("                                            aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Customer Database <span\n");
      out.write("                                            class=\"float-right\">60%</span></h4>\n");
      out.write("                                    <div class=\"progress mb-4\">\n");
      out.write("                                        <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 60%\"\n");
      out.write("                                            aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Payout Details <span\n");
      out.write("                                            class=\"float-right\">80%</span></h4>\n");
      out.write("                                    <div class=\"progress mb-4\">\n");
      out.write("                                        <div class=\"progress-bar bg-info\" role=\"progressbar\" style=\"width: 80%\"\n");
      out.write("                                            aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <h4 class=\"small font-weight-bold\">Account Setup <span\n");
      out.write("                                            class=\"float-right\">Complete!</span></h4>\n");
      out.write("                                    <div class=\"progress\">\n");
      out.write("                                        <div class=\"progress-bar bg-success\" role=\"progressbar\" style=\"width: 100%\"\n");
      out.write("                                            aria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Color System -->\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-primary text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Primary\n");
      out.write("                                            <div class=\"text-white-50 small\">#4e73df</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-success text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Success\n");
      out.write("                                            <div class=\"text-white-50 small\">#1cc88a</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-info text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Info\n");
      out.write("                                            <div class=\"text-white-50 small\">#36b9cc</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-warning text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Warning\n");
      out.write("                                            <div class=\"text-white-50 small\">#f6c23e</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-danger text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Danger\n");
      out.write("                                            <div class=\"text-white-50 small\">#e74a3b</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-secondary text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Secondary\n");
      out.write("                                            <div class=\"text-white-50 small\">#858796</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-light text-black shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Light\n");
      out.write("                                            <div class=\"text-black-50 small\">#f8f9fc</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-lg-6 mb-4\">\n");
      out.write("                                    <div class=\"card bg-dark text-white shadow\">\n");
      out.write("                                        <div class=\"card-body\">\n");
      out.write("                                            Dark\n");
      out.write("                                            <div class=\"text-white-50 small\">#5a5c69</div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-lg-6 mb-4\">\n");
      out.write("\n");
      out.write("                            <!-- Illustrations -->\n");
      out.write("                            <div class=\"card shadow mb-4\">\n");
      out.write("                                <div class=\"card-header py-3\">\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Illustrations</h6>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"text-center\">\n");
      out.write("                                        <img class=\"img-fluid px-3 px-sm-4 mt-3 mb-4\" style=\"width: 25rem;\"\n");
      out.write("                                            src=\"img/undraw_posting_photo.svg\" alt=\"...\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <p>Add some quality, svg illustrations to your project courtesy of <a\n");
      out.write("                                            target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">unDraw</a>, a\n");
      out.write("                                        constantly updated collection of beautiful svg images that you can use\n");
      out.write("                                        completely free and without attribution!</p>\n");
      out.write("                                    <a target=\"_blank\" rel=\"nofollow\" href=\"https://undraw.co/\">Browse Illustrations on\n");
      out.write("                                        unDraw &rarr;</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Approach -->\n");
      out.write("                            <div class=\"card shadow mb-4\">\n");
      out.write("                                <div class=\"card-header py-3\">\n");
      out.write("                                    <h6 class=\"m-0 font-weight-bold text-primary\">Development Approach</h6>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce\n");
      out.write("                                        CSS bloat and poor page performance. Custom CSS classes are used to create\n");
      out.write("                                        custom components and custom utility classes.</p>\n");
      out.write("                                    <p class=\"mb-0\">Before working with this theme, you should become familiar with the\n");
      out.write("                                        Bootstrap framework, especially the utility classes.</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <!-- /.container-fluid -->\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!-- End of Main Content -->\n");
      out.write("\n");
      out.write("            <!-- Footer -->\n");
      out.write("\n");
      out.write(" <!-- Footer -->\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\n");
      out.write("                <div class=\"container my-auto\">\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\n");
      out.write("                        <span>Copyright &copy; Your Website 2021</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </footer>\n");
      out.write("            <!-- End of Footer -->\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- End of Content Wrapper -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- End of Page Wrapper -->\n");
      out.write("\n");
      out.write("    <!-- Scroll to Top Button-->\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\n");
      out.write("    </a>\n");
      out.write("\n");
      out.write("    <!-- Logout Modal-->\n");
      out.write("    <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("        aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                        <span aria-hidden=\"true\">×</span>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("           \n");
      out.write("            <!-- End of Footer -->\n");
      out.write("            <!-- Bootstrap core JavaScript-->\n");
      out.write("    <script src=\"/resources/pages/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("    <script src=\"/resources/pages/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Core plugin JavaScript-->\n");
      out.write("    <script src=\"/resources/pages/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom scripts for all pages-->\n");
      out.write("    <script src=\"/resources/pages/js/sb-admin-2.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Page level plugins -->\n");
      out.write("    <script src=\"/resources/pages/vendor/chart.js/Chart.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Page level custom scripts -->\n");
      out.write("    <script src=\"/resources/pages/js/demo/chart-area-demo.js\"></script>\n");
      out.write("    <script src=\"/resources/pages/js/demo/chart-pie-demo.js\"></script>\n");
      out.write("<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("       ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
