/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-15 04:49:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/jeong-gwang-yeong/Documents/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/nkidol/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/Users/jeong-gwang-yeong/Documents/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/nkidol/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673125571922L));
    _jspx_dependants.put("/layout/navbar.jsp", Long.valueOf(1673734951000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("	\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("<link type=\"text/css;\" rel=\"stylesheet\" href=\"/css/style.css\" />\n");
      out.write("<title>日韓アイドル</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-light shadow-lg sticky-top\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<a class=\"navbar-brand \" href=\"/main\"><img src=\"/images/logo.png\"\n");
      out.write("				alt=\"\" /></a>\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("				aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("						aria-current=\"page\" href=\"/main\">ホーム</a></li>\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle text-primary\" \n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" disabled>\n");
      out.write("							韓アイドル </a>\n");
      out.write("						<ul class=\"dropdown-menu dropend\">\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\" >１９９０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=1990&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=1990&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０００年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=2000&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=2000&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０１０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=2010&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=2010&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０２０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/korea?year=2020&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/korea?year=2020&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li class=\"nav-item dropdown\"><a\n");
      out.write("						class=\"nav-link dropdown-toggle text-danger\" disabled\n");
      out.write("						role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("							日アイドル </a>\n");
      out.write("						<ul class=\"dropdown-menu dropend\">\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">１９９０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=1990&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=1990&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０００年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=2000&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=2000&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０１０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=2010&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=2010&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><hr class=\"dropdown-divider\"></li>\n");
      out.write("							<li><a class=\"dropdown-item dropdown-toggle\" role=\"button\">２０２０年代</a>\n");
      out.write("								<ul class=\"dropdown-menu submenu\">\n");
      out.write("									<li><a href=\"/album/japan?year=2020&gen=boy\" class=\"dropdown-item\">BoyGroup</a></li>\n");
      out.write("									<li><a href=\"/album/japan?year=2020&gen=girl\" class=\"dropdown-item\">GirlGroup</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"/board/list\">掲示板</a>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content rounded-4 shadow\">\n");
      out.write("				<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("					<h1 class=\"fw-bold mb-0 fs-2\">ログイン</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"modal-body p-5 pt-0\">\n");
      out.write("					<form action=\"/user/login\"\n");
      out.write("						onsubmit=\"loginFormSubmit(this); return false;\" method=\"post\">\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputLoginId\"\n");
      out.write("								name=\"userID\" placeholder=\"ID\"> <label\n");
      out.write("								for=\"floatingInputLoginId\">ID</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"password\" class=\"form-control rounded-3\"\n");
      out.write("								id=\"floatingLoginPassword\" name=\"userPassword\" placeholder=\"Password\">\n");
      out.write("							<label for=\"floatingLoginPassword\">PASSWORD</label>\n");
      out.write("						</div>\n");
      out.write("						<button class=\"w-100 mb-2 btn btn-lg rounded-3 btn-primary\"\n");
      out.write("							type=\"submit\">LOG IN</button>\n");
      out.write("						<hr class=\"my-4\">\n");
      out.write("						<ul>\n");
      out.write("						<li><a class=\"text-primary\" role=\"button\" data-bs-target=\"#findById\" data-bs-toggle=\"modal\"\n");
      out.write("						>IDを忘れた方はこちら</a></li>\n");
      out.write("						<li><a class=\"text-primary\" role=\"button\" data-bs-target=\"#findByPw\" data-bs-toggle=\"modal\"\n");
      out.write("						>PASSWORDを忘れた方はこちら</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"modal fade\" id=\"findById\"  tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" >\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content rounded-4 shadow\">\n");
      out.write("				<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("					<h1 class=\"fw-bold mb-0 fs-2\">IDを忘れた方</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"modal-body p-5 pt-0\">\n");
      out.write("					<form action=\"/user/findById\"\n");
      out.write("						onsubmit=\"findByIdFormSubmit(this); return false;\" method=\"post\">\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<div class=\"form-floating mb-3 col\">\n");
      out.write("							<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputFirst\"\n");
      out.write("								name=\"userFirstName\" placeholder=\"FirstName\"><label\n");
      out.write("								for=\"floatingInputFirst\">FirstName</label>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-floating col\">\n");
      out.write("								<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputLast\"\n");
      out.write("								name=\"userLastName\" placeholder=\"LastName\"><label\n");
      out.write("								for=\"floatingInputLast\">LastName</label>\n");
      out.write("								</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"email\" class=\"form-control rounded-3\"\n");
      out.write("								id=\"floatingEmail\" name=\"userEmail\" placeholder=\"E-mail\">\n");
      out.write("							<label for=\"floatingEmail\">E-mail</label>\n");
      out.write("						</div>\n");
      out.write("						<button class=\"w-100 mb-2 btn btn-lg rounded-3 btn-primary\"\n");
      out.write("							type=\"submit\">送信</button>\n");
      out.write("					</form>\n");
      out.write("						<hr class=\"my-4\">\n");
      out.write("						<a class=\"text-primary\" role=\"button\" data-bs-target=\"#findByPw\" data-bs-toggle=\"modal\"\n");
      out.write("						>PASSWORDを忘れた方はこちら</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div><div class=\"modal fade\" id=\"findByPw\"  tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\" >\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content rounded-4 shadow\">\n");
      out.write("				<div class=\"modal-header p-5 pb-4 border-bottom-0\">\n");
      out.write("					<h1 class=\"fw-bold mb-0 fs-2\">Passwordを忘れた方</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"modal-body p-5 pt-0\">\n");
      out.write("					<form action=\"/user/findByPw\"\n");
      out.write("						onsubmit=\"findByPwFormSubmit(this); return false;\" method=\"post\">\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"text\" autofocus\n");
      out.write("								class=\"form-control rounded-3 myInput\" id=\"floatingInputFindPw\"\n");
      out.write("								name=\"userID\" placeholder=\"ID\"> <label\n");
      out.write("								for=\"floatingInputFindPw\">ID</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-floating mb-3\">\n");
      out.write("							<input type=\"email\" class=\"form-control rounded-3\"\n");
      out.write("								id=\"floatingFindPwEmail\" name=\"userEmail\" placeholder=\"E-mail\">\n");
      out.write("							<label for=\"floatingFindPwEmail\">E-mail</label>\n");
      out.write("						</div>\n");
      out.write("						<button class=\"w-100 mb-2 btn btn-lg rounded-3 btn-primary\"\n");
      out.write("							type=\"submit\">送信</button>\n");
      out.write("					</form>\n");
      out.write("						<hr class=\"my-4\">\n");
      out.write("						<a class=\"text-primary\" role=\"button\" data-bs-target=\"#findById\" data-bs-toggle=\"modal\"\n");
      out.write("						>IDを忘れた方はこちら</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>");
      out.write("\n");
      out.write("	<div class=\"container py-4\">\n");
      out.write("		<div class=\"row mt-4\">\n");
      out.write("			<div class=\"col-sm-5\">\n");
      out.write("				<div class=\"fs-1\">\n");
      out.write("					<img src=\"images/korea.png\" alt=\"\" />韓アイドル\n");
      out.write("				</div>\n");
      out.write("				<div id=\"carouselExampleSlidesOnly\" class=\"carousel slide\"\n");
      out.write("					data-bs-ride=\"carousel\">\n");
      out.write("					<div class=\"carousel-inner border p-2\">\n");
      out.write("						<div class=\"carousel-item active\" data-bs-interval=\"2000\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kList.get(0).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"carousel-item \">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kList.get(1).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"carousel-item\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kList.get(2).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("								class=\"d-block w-100 lesse\" alt=\"...\">\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-sm-5 offset-sm-2\">\n");
      out.write("				<div class=\"fs-1\">\n");
      out.write("					<img src=\"images/japan.png\" alt=\"\" />日アイドル\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div id=\"carouselExampleSlidesOnly\" class=\"carousel slide\"\n");
      out.write("					data-bs-ride=\"carousel\">\n");
      out.write("					<div class=\"carousel-inner badge border p-2\">\n");
      out.write("						<div class=\"carousel-item active\" data-bs-interval=\"2000\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jList.get(0).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\"\n");
      out.write("								alt=\"...\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"carousel-item\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jList.get(1).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\"\n");
      out.write("								alt=\"...\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"carousel-item\">\n");
      out.write("							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jList.get(2).filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"d-block w-100\"\n");
      out.write("								alt=\"...\">\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"/js/app.js\"></script>\n");
      out.write("	<script src=\"/js/modalFocus.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /layout/navbar.jsp(107,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty principal}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"nav-item dropdown pe-3\">\n");
          out.write("						<button class=\"btn btn-primary dropdown-toggle\" type=\"button\"\n");
          out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">ログイン</button>\n");
          out.write("						<ul class=\"dropdown-menu\">\n");
          out.write("							<li><a class=\"dropdown-item text-start\" role=\"button\" data-bs-toggle=\"modal\"\n");
          out.write("								data-bs-target=\"#myModal\" aria-expanded=\"false\">ログイン</a></li>\n");
          out.write("							<li><a class=\"dropdown-item text-start\" href=\"/user/join_view\">会員登録</a></li>\n");
          out.write("						</ul>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /layout/navbar.jsp(118,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty principal}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div class=\"nav-item dropdown\">\n");
          out.write("						");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("						<button class=\"btn btn-primary dropdown-toggle\" type=\"button\"\n");
          out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\">会員管理</button>\n");
          out.write("						<ul class=\"dropdown-menu dropdown-menu-end\">\n");
          out.write("							<li class=\"dropdown-divider\"></li>\n");
          out.write("\n");
          out.write("							<li><a class=\"dropdown-item text-start\" href=\"/user/logout\">ログアウト</a></li>\n");
          out.write("						</ul>\n");
          out.write("					</div>\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /layout/navbar.jsp(120,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!isEmailCheck}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							<a href=\"/user/emailSend\" class=\"btn btn-danger\" role=\"button\"\n");
          out.write("								onclick=\"clickEmailSendMSG();\">E-MAIL確認</a>\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
